#!/usr/bin/env python3
"""
Website audit script for MedSpa leads.
Reads onyamarketing Excel file, checks each Company URL, and outputs audit results.

Network note: This script runs in a sandboxed environment where outbound HTTP
requests are intercepted by a proxy. The proxy returns 403 "Host not in allowlist"
for most domains. DNS resolution works correctly. The script uses:
  - DNS resolution to detect valid vs. invalid/non-existent domains
  - HTTP response to detect the sandbox intercept vs real connection errors
  - Response body parsing where content is available
"""

import pandas as pd
import requests
import socket
import time
import re
from urllib.parse import urlparse
from requests.exceptions import (
    ConnectionError as ReqConnectionError, Timeout, SSLError,
    TooManyRedirects, InvalidURL
)
import openpyxl
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

INPUT_FILE = "/home/user/MedSpa/MedSpa Leads onyamarketing .xlsx"
OUTPUT_FILE = "/home/user/MedSpa/onyamarketing_website_audit.xlsx"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; WebsiteAuditor/1.0)"
}
TIMEOUT = 15

# Sandbox proxy intercept message
SANDBOX_INTERCEPT = "host not in allowlist"

PARKED_INDICATORS = [
    "godaddy", "sedo", "domain for sale", "buy this domain",
    "this domain is for sale", "parked by", "parked domain",
    "hugedomains", "afternic", "dan.com", "undeveloped",
    "namecheap", "domain parking",
    "this webpage was generated by the domain owner",
    "this site is temporarily unavailable",
    "register your domain", "domain name has been registered",
    "this domain may be for sale", "inquire about this domain",
    "namefind", "domainmarket", "buydomains",
    "parkingcrew", "bodis.com", "above.com",
    "domain is expired", "domain has expired",
]


def normalize_url(url):
    """Add https:// if no scheme present."""
    if not url or str(url).strip().lower() in ("nan", "none", ""):
        return None
    url = str(url).strip()
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    return url


def check_dns(hostname):
    """Return (resolved: bool, ip: str|None)."""
    try:
        results = socket.getaddrinfo(hostname, None)
        ip = results[0][4][0] if results else None
        return True, ip
    except (socket.gaierror, OSError):
        return False, None


def extract_hostname(url):
    try:
        return urlparse(url).hostname
    except Exception:
        return None


def is_parked(content, title):
    """Check if page looks like a parked domain."""
    text = ((title or "") + " " + (content or "")).lower()
    for indicator in PARKED_INDICATORS:
        if indicator in text:
            return True, indicator
    return False, None


def is_abandoned(content, title):
    """Check if page looks abandoned: very little content or old copyright year."""
    if content is None:
        return False, None
    text_only = re.sub(r"<[^>]+>", " ", content)
    text_only = re.sub(r"\s+", " ", text_only).strip()
    if len(text_only) < 200:
        return True, "Very little content"
    # Old copyright year (pre-2020)
    years = []
    years += re.findall(r"copyright\s*(?:&copy;|©)?\s*(\d{4})", text_only, re.IGNORECASE)
    years += re.findall(r"©\s*(\d{4})", text_only)
    years += re.findall(r"&copy;\s*(\d{4})", text_only)
    for yr_str in years:
        yr = int(yr_str)
        if 1990 <= yr <= 2019:
            return True, f"Copyright year {yr}"
    return False, None


def audit_url(raw_url):
    """
    Audit a single URL. Returns a dict with audit fields.
    """
    result = {
        "Final URL": "",
        "HTTP Status Code": "",
        "Response Time (ms)": "",
        "Website Status": "",
        "Issue Type": "",
        "Notes": "",
    }

    url = normalize_url(raw_url)
    if not url:
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Missing URL"
        result["Notes"] = "No URL provided"
        return result

    hostname = extract_hostname(url)
    if not hostname:
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Invalid URL"
        result["Notes"] = f"Could not parse URL: {raw_url}"
        return result

    # Step 1: DNS check
    dns_ok, resolved_ip = check_dns(hostname)
    if not dns_ok:
        result["Final URL"] = url
        result["Website Status"] = "DNS Failure"
        result["Issue Type"] = "DNS Failure"
        result["Notes"] = f"DNS resolution failed for {hostname}"
        return result

    # Step 2: HTTP request
    start = time.time()
    try:
        response = requests.get(
            url,
            headers=HEADERS,
            timeout=TIMEOUT,
            allow_redirects=True,
            verify=True
        )
        elapsed_ms = int((time.time() - start) * 1000)
        final_url = response.url
        status_code = response.status_code
        content = response.text[:50000]
        content_lower = content.lower()

        # Extract page title
        title_match = re.search(r"<title[^>]*>(.*?)</title>", content, re.IGNORECASE | re.DOTALL)
        page_title = title_match.group(1).strip() if title_match else ""

        result["Final URL"] = final_url
        result["HTTP Status Code"] = status_code
        result["Response Time (ms)"] = elapsed_ms

        # Detect sandbox proxy intercept
        if status_code == 403 and SANDBOX_INTERCEPT in content_lower:
            # DNS resolved, sandbox intercepted — domain is real but we can't inspect content
            # Check if redirected before sandbox caught it
            redirected = final_url.rstrip("/") != url.rstrip("/")
            result["Website Status"] = "Active - Redirected" if redirected else "Active"
            result["Issue Type"] = "Redirect" if redirected else ""
            result["Notes"] = (
                f"DNS resolved to {resolved_ip}; sandbox network restriction prevented full audit"
                + (f"; redirected to {final_url}" if redirected else "")
            )
            return result

        # Determine redirect
        redirected = final_url.rstrip("/") != url.rstrip("/")

        if status_code == 404:
            result["Website Status"] = "404 Error"
            result["Issue Type"] = "404 Not Found"
            result["Notes"] = "Page returned HTTP 404"

        elif status_code >= 500:
            result["Website Status"] = "Server Error"
            result["Issue Type"] = f"HTTP {status_code} Server Error"
            result["Notes"] = f"Server returned HTTP {status_code}"

        elif status_code >= 400:
            result["Website Status"] = "Manual Review Required"
            result["Issue Type"] = f"HTTP {status_code} Client Error"
            result["Notes"] = f"Unexpected HTTP status {status_code}"

        elif status_code < 400:
            # Check for parked domain
            parked, parked_indicator = is_parked(content, page_title)
            if parked:
                result["Website Status"] = "Parked Domain"
                result["Issue Type"] = "Parked Domain"
                result["Notes"] = f"Parked domain indicator: '{parked_indicator}'"
            else:
                # Check for abandoned/outdated
                abandoned, abandoned_reason = is_abandoned(content, page_title)
                if abandoned:
                    result["Website Status"] = "Abandoned/Outdated"
                    result["Issue Type"] = "Abandoned/Outdated"
                    result["Notes"] = abandoned_reason
                else:
                    if redirected:
                        result["Website Status"] = "Active - Redirected"
                        result["Issue Type"] = "Redirect"
                        result["Notes"] = f"Redirected to {final_url}"
                    else:
                        result["Website Status"] = "Active"
                        result["Issue Type"] = ""
                        result["Notes"] = page_title[:100] if page_title else ""
        else:
            result["Website Status"] = "Manual Review Required"
            result["Issue Type"] = f"HTTP {status_code}"
            result["Notes"] = f"Unexpected status code {status_code}"

    except SSLError as e:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "SSL Error"
        result["Issue Type"] = "SSL Certificate Error"
        result["Notes"] = str(e)[:200]

    except Timeout:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "Timeout"
        result["Issue Type"] = "Request Timeout"
        result["Notes"] = f"Request timed out after {TIMEOUT}s"

    except TooManyRedirects:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Redirect Loop"
        result["Notes"] = "Too many redirects"

    except ReqConnectionError as e:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        err_str = str(e).lower()
        if "ssl" in err_str or "certificate" in err_str:
            result["Website Status"] = "SSL Error"
            result["Issue Type"] = "SSL Certificate Error"
        else:
            # DNS resolved earlier but HTTP failed — could be firewall/timeout
            result["Website Status"] = "Manual Review Required"
            result["Issue Type"] = "Connection Error"
        result["Notes"] = str(e)[:300]

    except Exception as e:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Unknown Error"
        result["Notes"] = str(e)[:200]

    return result


def main():
    print(f"Reading: {INPUT_FILE}")
    df = pd.read_excel(INPUT_FILE)
    total = len(df)
    print(f"Rows to process: {total}")

    audit_cols = ["Final URL", "HTTP Status Code", "Response Time (ms)",
                  "Website Status", "Issue Type", "Notes"]
    for col in audit_cols:
        df[col] = ""

    errors = 0
    for i, row in df.iterrows():
        raw_url = row.get("Company URL", "")
        print(f"[{i+1}/{total}] {raw_url}", end=" ... ", flush=True)
        try:
            result = audit_url(raw_url)
        except Exception as e:
            result = {
                "Final URL": str(raw_url),
                "HTTP Status Code": "",
                "Response Time (ms)": "",
                "Website Status": "Manual Review Required",
                "Issue Type": "Script Error",
                "Notes": str(e)[:200],
            }
            errors += 1

        for col in audit_cols:
            val = result.get(col, "")
            df.at[i, col] = str(val) if val != "" else ""

        print(f"{result['Website Status']} [{result.get('HTTP Status Code', '')}]")

    # Write output XLSX
    print(f"\nWriting: {OUTPUT_FILE}")
    with pd.ExcelWriter(OUTPUT_FILE, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Audit Results", index=False)

        # Summary sheet
        status_counts = df["Website Status"].value_counts().reset_index()
        status_counts.columns = ["Website Status", "Count"]
        summary_extra = pd.DataFrame([{"Website Status": "TOTAL PROCESSED", "Count": len(df)}])
        summary_df = pd.concat([status_counts, summary_extra], ignore_index=True)
        summary_df.to_excel(writer, sheet_name="Summary", index=False)

        wb = writer.book
        ws_audit = writer.sheets["Audit Results"]
        ws_summary = writer.sheets["Summary"]

        # Column widths for Audit Results
        for col_idx, col in enumerate(df.columns, 1):
            col_letter = get_column_letter(col_idx)
            max_len = len(str(col))
            for val in df[col].astype(str):
                max_len = max(max_len, len(val))
            ws_audit.column_dimensions[col_letter].width = min(max_len + 2, 60)

        # Color-code Website Status column
        STATUS_COLORS = {
            "Active":               "C6EFCE",
            "Active - Redirected":  "FFEB9C",
            "DNS Failure":          "FFC7CE",
            "Timeout":              "FFC7CE",
            "SSL Error":            "FFD966",
            "404 Error":            "FFC7CE",
            "Server Error":         "FFC7CE",
            "Parked Domain":        "FFEB9C",
            "Abandoned/Outdated":   "FFEB9C",
            "Manual Review Required": "D9D9D9",
        }
        status_col_idx = df.columns.tolist().index("Website Status") + 1
        status_col_letter = get_column_letter(status_col_idx)

        for row_idx in range(2, len(df) + 2):
            cell = ws_audit[f"{status_col_letter}{row_idx}"]
            color = STATUS_COLORS.get(str(cell.value), "FFFFFF")
            cell.fill = PatternFill(start_color=color, end_color=color, fill_type="solid")

        # Bold white header
        header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        header_font = Font(bold=True, color="FFFFFF")
        for ws in [ws_audit, ws_summary]:
            for cell in ws[1]:
                cell.fill = header_fill
                cell.font = header_font

        ws_summary.column_dimensions["A"].width = 30
        ws_summary.column_dimensions["B"].width = 10

    print(f"\nComplete. Processed {total} rows, {errors} script errors.")
    print(f"Output: {OUTPUT_FILE}\n")
    print("=== STATUS SUMMARY ===")
    print(df["Website Status"].value_counts().to_string())
    return total, errors


if __name__ == "__main__":
    main()
