#!/usr/bin/env python3
"""
Website audit script for MedSpa leads.
Reads onyamarketing Excel file, checks each Company URL, and outputs audit results.
"""

import pandas as pd
import requests
import socket
import time
import re
import ssl
from urllib.parse import urlparse
from requests.exceptions import (
    ConnectionError, Timeout, SSLError, TooManyRedirects, InvalidURL
)
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

INPUT_FILE = "/home/user/MedSpa/MedSpa Leads onyamarketing .xlsx"
OUTPUT_FILE = "/home/user/MedSpa/onyamarketing_website_audit.xlsx"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; WebsiteAuditor/1.0)"
}
TIMEOUT = 15

PARKED_INDICATORS = [
    "godaddy", "sedo", "domain for sale", "buy this domain",
    "this domain is for sale", "parked by", "parked domain",
    "hugedomains", "afternic", "dan.com", "undeveloped",
    "namecheap", "domain parking", "this webpage was generated by the domain owner",
    "this site is temporarily unavailable", "click here to proceed to",
    "register your domain", "domain name has been registered",
    "this domain may be for sale", "inquire about this domain",
    "namefind", "domainmarket", "buydomains",
]

ABANDONED_INDICATORS = [
    # Copyright years before 2020
]


def normalize_url(url):
    """Add https:// if no scheme present."""
    if not url or str(url).strip().lower() in ("nan", "none", ""):
        return None
    url = str(url).strip()
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    return url


def check_dns(hostname):
    """Return True if hostname resolves."""
    try:
        socket.getaddrinfo(hostname, None)
        return True
    except (socket.gaierror, OSError):
        return False


def extract_hostname(url):
    try:
        return urlparse(url).hostname
    except Exception:
        return None


def is_parked(content, title):
    """Check if page looks like a parked domain."""
    text = ((title or "") + " " + (content or "")).lower()
    for indicator in PARKED_INDICATORS:
        if indicator in text:
            return True, indicator
    return False, None


def is_abandoned(content, title):
    """Check if page looks abandoned/outdated: very little content or old copyright year."""
    if content is None:
        return False, None
    # Very little visible text
    text_only = re.sub(r"<[^>]+>", " ", content)
    text_only = re.sub(r"\s+", " ", text_only).strip()
    if len(text_only) < 200:
        return True, "Very little content"
    # Old copyright year (pre-2020)
    years = re.findall(r"copyright\s*(?:&copy;|©)?\s*(\d{4})", text_only, re.IGNORECASE)
    years += re.findall(r"©\s*(\d{4})", text_only)
    years += re.findall(r"&copy;\s*(\d{4})", text_only)
    for yr_str in years:
        yr = int(yr_str)
        if 1990 <= yr <= 2019:
            return True, f"Copyright year {yr}"
    return False, None


def audit_url(raw_url):
    """
    Audit a single URL. Returns a dict with:
    final_url, http_status, response_time_ms, website_status, issue_type, notes
    """
    result = {
        "Final URL": "",
        "HTTP Status Code": "",
        "Response Time (ms)": "",
        "Website Status": "",
        "Issue Type": "",
        "Notes": "",
    }

    url = normalize_url(raw_url)
    if not url:
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Missing URL"
        result["Notes"] = "No URL provided"
        return result

    hostname = extract_hostname(url)
    if not hostname:
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Invalid URL"
        result["Notes"] = f"Could not parse URL: {raw_url}"
        return result

    # DNS check
    if not check_dns(hostname):
        result["Final URL"] = url
        result["Website Status"] = "DNS Failure"
        result["Issue Type"] = "DNS Failure"
        result["Notes"] = f"DNS resolution failed for {hostname}"
        return result

    # HTTP request
    start = time.time()
    try:
        response = requests.get(
            url,
            headers=HEADERS,
            timeout=TIMEOUT,
            allow_redirects=True,
            verify=True
        )
        elapsed_ms = int((time.time() - start) * 1000)
        final_url = response.url
        status_code = response.status_code
        content = response.text[:50000]  # limit to first 50k chars

        # Extract page title
        title_match = re.search(r"<title[^>]*>(.*?)</title>", content, re.IGNORECASE | re.DOTALL)
        page_title = title_match.group(1).strip() if title_match else ""

        result["Final URL"] = final_url
        result["HTTP Status Code"] = status_code
        result["Response Time (ms)"] = elapsed_ms

        # Determine if redirected
        redirected = final_url.rstrip("/") != url.rstrip("/")

        if status_code == 404:
            result["Website Status"] = "404 Error"
            result["Issue Type"] = "404 Not Found"
            result["Notes"] = "Page returned HTTP 404"

        elif status_code >= 500:
            result["Website Status"] = "Server Error"
            result["Issue Type"] = f"HTTP {status_code} Server Error"
            result["Notes"] = f"Server returned HTTP {status_code}"

        elif status_code >= 400:
            result["Website Status"] = "Manual Review Required"
            result["Issue Type"] = f"HTTP {status_code} Client Error"
            result["Notes"] = f"Unexpected HTTP status {status_code}"

        elif status_code == 200 or status_code in (301, 302, 303, 307, 308):
            # Check for parked domain
            parked, parked_indicator = is_parked(content, page_title)
            if parked:
                result["Website Status"] = "Parked Domain"
                result["Issue Type"] = "Parked Domain"
                result["Notes"] = f"Parked domain indicator found: '{parked_indicator}'"
            else:
                # Check for abandoned/outdated
                abandoned, abandoned_reason = is_abandoned(content, page_title)
                if abandoned:
                    result["Website Status"] = "Abandoned/Outdated"
                    result["Issue Type"] = "Abandoned/Outdated"
                    result["Notes"] = abandoned_reason
                else:
                    if redirected:
                        result["Website Status"] = "Active - Redirected"
                        result["Issue Type"] = "Redirect"
                        result["Notes"] = f"Redirected to {final_url}"
                    else:
                        result["Website Status"] = "Active"
                        result["Issue Type"] = ""
                        result["Notes"] = page_title[:100] if page_title else ""
        else:
            result["Website Status"] = "Manual Review Required"
            result["Issue Type"] = f"HTTP {status_code}"
            result["Notes"] = f"Unexpected status code {status_code}"

    except SSLError as e:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "SSL Error"
        result["Issue Type"] = "SSL Certificate Error"
        result["Notes"] = str(e)[:200]

    except Timeout:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "Timeout"
        result["Issue Type"] = "Request Timeout"
        result["Notes"] = f"Request timed out after {TIMEOUT}s"

    except TooManyRedirects:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Redirect Loop"
        result["Notes"] = "Too many redirects"

    except ConnectionError as e:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        err_str = str(e).lower()
        if "ssl" in err_str or "certificate" in err_str:
            result["Website Status"] = "SSL Error"
            result["Issue Type"] = "SSL Certificate Error"
        else:
            result["Website Status"] = "DNS Failure"
            result["Issue Type"] = "Connection Error"
        result["Notes"] = str(e)[:200]

    except Exception as e:
        elapsed_ms = int((time.time() - start) * 1000)
        result["Final URL"] = url
        result["Response Time (ms)"] = elapsed_ms
        result["Website Status"] = "Manual Review Required"
        result["Issue Type"] = "Unknown Error"
        result["Notes"] = str(e)[:200]

    return result


def main():
    print(f"Reading input file: {INPUT_FILE}")
    df = pd.read_excel(INPUT_FILE)
    total = len(df)
    print(f"Total rows to process: {total}")

    audit_cols = ["Final URL", "HTTP Status Code", "Response Time (ms)",
                  "Website Status", "Issue Type", "Notes"]
    for col in audit_cols:
        df[col] = ""

    errors = 0
    for i, row in df.iterrows():
        raw_url = row.get("Company URL", "")
        print(f"[{i+1}/{total}] Checking: {raw_url}", end=" ... ", flush=True)
        try:
            result = audit_url(raw_url)
        except Exception as e:
            result = {
                "Final URL": str(raw_url),
                "HTTP Status Code": "",
                "Response Time (ms)": "",
                "Website Status": "Manual Review Required",
                "Issue Type": "Script Error",
                "Notes": str(e)[:200],
            }
            errors += 1

        for col in audit_cols:
            df.at[i, col] = result.get(col, "")

        print(f"{result['Website Status']} ({result.get('HTTP Status Code', '')})")

    # Write output
    print(f"\nWriting output to: {OUTPUT_FILE}")
    with pd.ExcelWriter(OUTPUT_FILE, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Audit Results", index=False)

        # Summary sheet
        status_counts = df["Website Status"].value_counts().reset_index()
        status_counts.columns = ["Website Status", "Count"]
        total_processed = len(df)
        summary_extra = pd.DataFrame([
            {"Website Status": "TOTAL PROCESSED", "Count": total_processed}
        ])
        summary_df = pd.concat([status_counts, summary_extra], ignore_index=True)
        summary_df.to_excel(writer, sheet_name="Summary", index=False)

        # Format the Audit Results sheet
        wb = writer.book
        ws_audit = writer.sheets["Audit Results"]

        # Auto-width columns
        for col_idx, col in enumerate(df.columns, 1):
            col_letter = get_column_letter(col_idx)
            max_len = max(
                len(str(col)),
                df[col].astype(str).str.len().max() if len(df) > 0 else 0
            )
            ws_audit.column_dimensions[col_letter].width = min(max_len + 2, 50)

        # Color-code status column
        status_col_idx = df.columns.tolist().index("Website Status") + 1
        status_col_letter = get_column_letter(status_col_idx)

        STATUS_COLORS = {
            "Active": "C6EFCE",               # green
            "Active - Redirected": "FFEB9C",  # yellow
            "DNS Failure": "FFC7CE",           # red
            "Timeout": "FFC7CE",
            "SSL Error": "FFEB9C",
            "404 Error": "FFC7CE",
            "Server Error": "FFC7CE",
            "Parked Domain": "FFEB9C",
            "Abandoned/Outdated": "FFEB9C",
            "Manual Review Required": "D9D9D9",
        }

        for row_idx in range(2, len(df) + 2):  # skip header row
            cell = ws_audit[f"{status_col_letter}{row_idx}"]
            status_val = str(cell.value)
            color = STATUS_COLORS.get(status_val, "FFFFFF")
            cell.fill = PatternFill(start_color=color, end_color=color, fill_type="solid")

        # Bold header row
        for cell in ws_audit[1]:
            cell.font = Font(bold=True)
            cell.fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
            cell.font = Font(bold=True, color="FFFFFF")

        # Format Summary sheet
        ws_summary = writer.sheets["Summary"]
        for cell in ws_summary[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        ws_summary.column_dimensions["A"].width = 30
        ws_summary.column_dimensions["B"].width = 10

    print(f"\nDone. Processed {total} rows with {errors} script errors.")
    print(f"Output saved to: {OUTPUT_FILE}")

    # Print summary
    print("\n=== SUMMARY ===")
    print(df["Website Status"].value_counts().to_string())
    return total, errors


if __name__ == "__main__":
    main()
